/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/_layouts/app': RouteRecordInfo<'/_layouts/app', '/_layouts/app', Record<never, never>, Record<never, never>>,
    '/app/about': RouteRecordInfo<'/app/about', '/app/about', Record<never, never>, Record<never, never>>,
    '/app/student/delete-student': RouteRecordInfo<'/app/student/delete-student', '/app/student/delete-student', Record<never, never>, Record<never, never>>,
    '/app/student/register-student': RouteRecordInfo<'/app/student/register-student', '/app/student/register-student', Record<never, never>, Record<never, never>>,
    '/app/student/students': RouteRecordInfo<'/app/student/students', '/app/student/students', Record<never, never>, Record<never, never>>,
    '/app/student/update-student': RouteRecordInfo<'/app/student/update-student', '/app/student/update-student', Record<never, never>, Record<never, never>>,
  }
}
